### ISSUE TITLE
specify postgres version in installation?

### ISSUE THREAD

**Issue by jsms90** [macintoshhelper/learn-sql#4]
@macintoshhelper  I'm not sure whether this is necessary, or if `apt-get` will automatically take the most recent version?

But since students in FAC10 have had issues before, with having a version that was too old to use some postgres syntax, it might be prudent to specify `sudo apt-get -y install postgresql-9.6` in place of this in `setup.md`:
> sudo apt-get -y install postgresql postgresql-contrib

Note: [the docs](https://www.postgresql.org/download/linux/ubuntu/) suggest that `postgresql-contrib-9.6` automatically comes with `apt-get install postgresql-9.6`

**Comment by macintoshhelper** [comment]
If people do `apt-get update` before installing, it should update their package lists to have the latest version. It's probably best to avoid installing specific versions to avoid the need for frequent updates or the setup guide being out-of-date. 

I believe this may be caused by having outdated Ubuntu versions. `apt` often has outdated software packages, so I'll add instructions for setting up PostgreSQL's `apt` repository.

**Comment by jsms90** [comment]
Beautiful :heart:
